project:
  type: website

website:
  title: "CRI Bioinformatics Workshop"
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/CancerResearch
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/crigrants/CRI_bioinformatics_workshop
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: More Resources
  sidebar:
    style: docked
    contents: tutorials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
