project:
  type: website

website:
  title: "CRI Bioinformatics Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
