project:
  type: website

website:
  title: "CRI Bioinformatics Workshop"
  page-navigation: true
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/CancerResearch
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/crigrants/CRI_bioinformatics_workshop
    left:
      - text: "Home"
        file: index.qmd
      - text: "Course"
        file: course.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Authors"
        file: authors.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Acknowledgements"
        file: acknowledge.qmd
        
  sidebar:
    - title: "Course"
      style: "docked"
      search: true
      contents: 
        - section: "Intro to R"
          contents: 
            - course/1_introR.qmd
            - course/2_basicplotting.qmd
            - course/3_clustering.qmd
            - course/4_qctrouble.qmd
        - section: "Spatial Analysis"
          contents: 
            - course/python_tutorial.ipynb
            - course/spatial_demo.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
